name: Backend CI

on:
  push:
    branches:
      - working-demo
  workflow_dispatch:

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/ubuntu/freshnest-backend
            git pull origin working-demo
            npm install
